home:
  ssid: <YOUR_WLAN_SSID>
nas:
  nasserver_prod: <NAS_HOST>
  homedrive_prod: //<NAS_HOST>/<PATH>
  familyshare_prod: //<NAS_HOST>/<PATH>
  autohome_prod: //<NAS_HOST>/<PATH>
  home_mountpoint_prod: <LOCAL_MOUNTPOINT_1>
  family_mountpoint_prod: <LOCAL_MOUNTPOINT_2>
  third_mountpoint_prod: <LOCAL_MOUNTPOINT_3>
  user_prod: <NAS_USER>
  password_prod: <NAS_USER_PASSWORD>
  nasserver_bak: <NAS_HOST>
  homedrive_bak: //<NAS_HOST>/<PATH>
  mountpoint_bak: <LOCAL_MOUNTPOINT>
  user_bak: <NAS_USER>
  password_bak: <NAS_USER_PASSWORD>
luser:
  luid: <LOCAL_UID>
  lgid: <LOCAL_GID>
vpn:
  vconnection: <YOUR_VPN_CONNECTION>
  
